parameters:
#    poquete_api.example.class: Poquete\APIBundle\Example

services:
#    poquete_api.example:
#        class: %poquete_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
